import React from "react";
import { Flex, Box, Text } from "@radix-ui/themes";
import "./ScheduleGrid";
import ScheduleGrid from "./ScheduleGrid";

const ScheduleGridList = () => {
  const data = {
    schedules: [
      {
        periods: [
          {
            courseId: "530-HSA-VA",
            day: "Thu.",
            id: 8773,
            intensive: false,
            name: "Introduction to Cinema",
            seats: 0,
            section: "00002",
            teacherId: 2075,
            time: "8:30 - 11:30",
          },
          {
            courseId: "602-HSY-VA",
            day: "Fri.",
            id: 9104,
            intensive: false,
            name: "L'artiste citoyen",
            seats: 0,
            section: "00003",
            teacherId: 2130,
            time: "14:00 - 17:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Mon.",
            id: 9439,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Wed.",
            id: 9440,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "345-HSA-VA",
            day: "Thu.",
            id: 8073,
            intensive: false,
            name: "The Ethics of Responsibiity",
            seats: 0,
            section: "00005",
            teacherId: 1977,
            time: "11:30 - 14:30",
          },
          {
            courseId: "109-103-MQ",
            day: "Mon.",
            id: 6388,
            intensive: false,
            name: "Soccer",
            seats: 0,
            section: "00014",
            teacherId: 1727,
            time: "16:00 - 18:00",
          },
        ],
        score: 86.26097105508869,
      },
      {
        periods: [
          {
            courseId: "530-HSA-VA",
            day: "Thu.",
            id: 8773,
            intensive: false,
            name: "Introduction to Cinema",
            seats: 0,
            section: "00002",
            teacherId: 2075,
            time: "8:30 - 11:30",
          },
          {
            courseId: "602-HSY-VA",
            day: "Tue.",
            id: 9102,
            intensive: false,
            name: "Une planète en danger…",
            seats: 0,
            section: "00001",
            teacherId: 2129,
            time: "14:30 - 17:30",
          },
          {
            courseId: "603-HSD-VA",
            day: "Mon.",
            id: 9439,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Wed.",
            id: 9440,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "345-HSA-VA",
            day: "Thu.",
            id: 8073,
            intensive: false,
            name: "The Ethics of Responsibiity",
            seats: 0,
            section: "00005",
            teacherId: 1977,
            time: "11:30 - 14:30",
          },
          {
            courseId: "109-103-MQ",
            day: "Mon.",
            id: 6388,
            intensive: false,
            name: "Soccer",
            seats: 0,
            section: "00014",
            teacherId: 1727,
            time: "16:00 - 18:00",
          },
        ],
        score: 85.95219421101774,
      },
      {
        periods: [
          {
            courseId: "530-HSA-VA",
            day: "Thu.",
            id: 8773,
            intensive: false,
            name: "Introduction to Cinema",
            seats: 0,
            section: "00002",
            teacherId: 2075,
            time: "8:30 - 11:30",
          },
          {
            courseId: "602-HSY-VA",
            day: "Fri.",
            id: 9104,
            intensive: false,
            name: "L'artiste citoyen",
            seats: 0,
            section: "00003",
            teacherId: 2130,
            time: "14:00 - 17:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Mon.",
            id: 9439,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Wed.",
            id: 9440,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "345-HSA-VA",
            day: "Thu.",
            id: 8073,
            intensive: false,
            name: "The Ethics of Responsibiity",
            seats: 0,
            section: "00005",
            teacherId: 1977,
            time: "11:30 - 14:30",
          },
          {
            courseId: "109-103-MQ",
            day: "Wed.",
            id: 6407,
            intensive: false,
            name: "Fitness",
            seats: 0,
            section: "00026",
            teacherId: 1742,
            time: "16:00 - 18:00",
          },
        ],
        score: 85.91652661064424,
      },
      {
        periods: [
          {
            courseId: "530-HSA-VA",
            day: "Thu.",
            id: 8773,
            intensive: false,
            name: "Introduction to Cinema",
            seats: 0,
            section: "00002",
            teacherId: 2075,
            time: "8:30 - 11:30",
          },
          {
            courseId: "602-HSY-VA",
            day: "Fri.",
            id: 9104,
            intensive: false,
            name: "L'artiste citoyen",
            seats: 0,
            section: "00003",
            teacherId: 2130,
            time: "14:00 - 17:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Mon.",
            id: 9439,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Wed.",
            id: 9440,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "345-HSA-VA",
            day: "Thu.",
            id: 8073,
            intensive: false,
            name: "The Ethics of Responsibiity",
            seats: 0,
            section: "00005",
            teacherId: 1977,
            time: "11:30 - 14:30",
          },
          {
            courseId: "109-103-MQ",
            day: "Thu.",
            id: 6413,
            intensive: false,
            name: "Racquet Sports",
            seats: 0,
            section: "00031",
            teacherId: 1746,
            time: "16:00 - 18:00",
          },
        ],
        score: 85.90336871590742,
      },
      {
        periods: [
          {
            courseId: "530-HSA-VA",
            day: "Thu.",
            id: 8773,
            intensive: false,
            name: "Introduction to Cinema",
            seats: 0,
            section: "00002",
            teacherId: 2075,
            time: "8:30 - 11:30",
          },
          {
            courseId: "602-HSY-VA",
            day: "Fri.",
            id: 9104,
            intensive: false,
            name: "L'artiste citoyen",
            seats: 0,
            section: "00003",
            teacherId: 2130,
            time: "14:00 - 17:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Mon.",
            id: 9439,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "603-HSD-VA",
            day: "Wed.",
            id: 9440,
            intensive: false,
            name: "Rhymes with Relativity",
            seats: 0,
            section: "00004",
            teacherId: 2166,
            time: "14:00 - 16:00",
          },
          {
            courseId: "345-HSA-VA",
            day: "Thu.",
            id: 8073,
            intensive: false,
            name: "The Ethics of Responsibiity",
            seats: 0,
            section: "00005",
            teacherId: 1977,
            time: "11:30 - 14:30",
          },
          {
            courseId: "109-103-MQ",
            day: "Tue.",
            id: 6400,
            intensive: false,
            name: "Group Fitness",
            seats: 0,
            section: "00021",
            teacherId: 1729,
            time: "16:00 - 18:00",
          },
        ],
        score: 85.63641456582633,
      },
    ],
    teacherRatings: {
      1727: {
        avgRating: 90.0,
        links: [
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/gregory-longtin",
        ],
        name: " Gregory Longtin",
      },
      1729: {
        avgRating: null,
        links: [],
        name: " Jessica Braul",
      },
      1742: {
        avgRating: null,
        links: [
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/thomas-edward-oljemark",
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/tom-oljemark",
        ],
        name: " Thomas Edward Oljemark",
      },
      1746: {
        avgRating: null,
        links: [],
        name: " Julie Lynn Pigott",
      },
      1977: {
        avgRating: 94.0,
        links: [
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/gordon-aronoff",
        ],
        name: " Gordon Aronoff",
      },
      2075: {
        avgRating: 52.0,
        links: [
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/stefik",
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/dan-stefik",
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/daniel-stefik",
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/daniel-w-stefik",
        ],
        name: " Daniel W. Stefik",
      },
      2129: {
        avgRating: 76.0,
        links: [
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/isabelle-rivest",
        ],
        name: " Isabelle Rivest",
      },
      2130: {
        avgRating: null,
        links: [],
        name: " Anne L'Allier",
      },
      2166: {
        avgRating: 100.0,
        links: [
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/marianne-lynch",
          "https://ratemyteachers.com/ca/quebec/montreal/vanier-college/lynch-marianne-marianne",
        ],
        name: " Marianne Lynch",
      },
    },
  };
  return (
    <Flex direction="column" height="500vh">
      {data.schedules.map((schedule, index) => (
        <ScheduleGrid
          key={index}
          coursesData={schedule.periods}
          teacherRatingsData={data.teacherRatings}
          scheduleScore={schedule.score}
        ></ScheduleGrid>
      ))}
    </Flex>
  );
};

export default ScheduleGridList;
